
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { ExternalLink, Play, BookOpen, Clock, Award, Lock } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface LMSCourse {
  id: string;
  title: string;
  description: string;
  progress: number;
  totalLessons: number;
  completedLessons: number;
  duration: string;
  instructor: string;
  lmsUrl: string;
  isAccessible: boolean;
  certificateAvailable: boolean;
}

interface LMSIntegrationProps {
  courses: LMSCourse[];
}

const LMSIntegration: React.FC<LMSIntegrationProps> = ({ courses }) => {
  const [isLoading, setIsLoading] = useState<string | null>(null);
  const { toast } = useToast();

  const handleAccessCourse = async (course: LMSCourse) => {
    if (!course.isAccessible) {
      toast({
        title: "Access Restricted",
        description: "This course is not yet available. Please check back later.",
        variant: "destructive"
      });
      return;
    }

    setIsLoading(course.id);
    
    try {
      // Simulate API call to authenticate with LMS
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Open LMS in new tab with authentication token
      const lmsUrl = `${course.lmsUrl}?token=${generateAuthToken()}&user_id=${getCurrentUserId()}`;
      window.open(lmsUrl, '_blank');
      
      toast({
        title: "Course Opened",
        description: `Opening ${course.title} in the learning platform...`,
      });
    } catch (error) {
      toast({
        title: "Access Error",
        description: "Failed to access the course. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(null);
    }
  };

  const generateAuthToken = () => {
    // In a real implementation, this would be generated by your backend
    return 'demo_token_' + Date.now();
  };

  const getCurrentUserId = () => {
    // Get current user ID from your auth context
    return 'user_123';
  };

  return (
    <div className="space-y-4">
      {courses.map((course) => (
        <Card key={course.id} className="overflow-hidden">
          <CardContent className="p-6">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <BookOpen className="h-5 w-5 text-blue-600" />
                  <h3 className="font-semibold text-lg">{course.title}</h3>
                  {!course.isAccessible && (
                    <Lock className="h-4 w-4 text-gray-400" />
                  )}
                </div>
                
                <p className="text-gray-600 text-sm mb-3">{course.description}</p>
                
                <div className="flex items-center gap-4 text-sm text-gray-500 mb-3">
                  <div className="flex items-center gap-1">
                    <Clock className="h-4 w-4" />
                    <span>{course.duration}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Play className="h-4 w-4" />
                    <span>{course.completedLessons}/{course.totalLessons} lessons</span>
                  </div>
                  {course.certificateAvailable && (
                    <div className="flex items-center gap-1">
                      <Award className="h-4 w-4 text-yellow-500" />
                      <span>Certificate available</span>
                    </div>
                  )}
                </div>

                <div className="mb-4">
                  <div className="flex justify-between text-sm mb-1">
                    <span>Progress</span>
                    <span>{course.progress}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div 
                      className="bg-blue-600 h-2 rounded-full transition-all duration-300" 
                      style={{ width: `${course.progress}%` }}
                    ></div>
                  </div>
                </div>

                <p className="text-sm text-gray-600 mb-4">
                  Instructor: {course.instructor}
                </p>
              </div>

              <div className="flex flex-col gap-2 ml-4">
                <Button
                  onClick={() => handleAccessCourse(course)}
                  disabled={!course.isAccessible || isLoading === course.id}
                  className="flex items-center gap-2"
                >
                  {isLoading === course.id ? (
                    <>
                      <div className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
                      Opening...
                    </>
                  ) : (
                    <>
                      <ExternalLink className="h-4 w-4" />
                      {course.progress > 0 ? 'Continue' : 'Start'} Course
                    </>
                  )}
                </Button>

                <Dialog>
                  <DialogTrigger asChild>
                    <Button variant="outline" size="sm">
                      Course Info
                    </Button>
                  </DialogTrigger>
                  <DialogContent className="max-w-md">
                    <DialogHeader>
                      <DialogTitle>{course.title}</DialogTitle>
                      <DialogDescription>
                        Course details and progress information
                      </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4">
                      <div>
                        <h4 className="font-medium mb-2">Course Description</h4>
                        <p className="text-sm text-gray-600">{course.description}</p>
                      </div>
                      <div>
                        <h4 className="font-medium mb-2">Progress Details</h4>
                        <div className="space-y-2 text-sm">
                          <div className="flex justify-between">
                            <span>Completed Lessons:</span>
                            <span>{course.completedLessons}/{course.totalLessons}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Overall Progress:</span>
                            <span>{course.progress}%</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Estimated Duration:</span>
                            <span>{course.duration}</span>
                          </div>
                        </div>
                      </div>
                      {course.certificateAvailable && (
                        <div>
                          <h4 className="font-medium mb-2">Certification</h4>
                          <p className="text-sm text-gray-600">
                            Complete this course to earn a certificate of completion.
                          </p>
                        </div>
                      )}
                    </div>
                  </DialogContent>
                </Dialog>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
};

export default LMSIntegration;
